import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUI } from "@/providers/NextUI";
import TopNavbar from "@/components/TopNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Safe-bite",
  description: "Generated by create next app",
  icons: {
    icon: "/safebite-logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} prose-sm sm:prose-base prose-headings:m-0 prose-p:m-0 prose-ul:m-0 prose-img:m-0 prose-hr:my-5`}
      >
        <NextUI>
          <TopNavbar />
          {children}
        </NextUI>
      </body>
    </html>
  );
}
